### ISSUE TITLE
object has no attribute 'name'

### ISSUE THREAD

**Issue by copyfile** [feram18/led-stock-ticker#16]
Since yesterday I have the following error (again). I think it is exactly the same one as a couple of weeks ago. Any idea how to solve this now?

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-21:
Traceback (most recent call last):
Exception in thread Thread-20:
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    self.run()
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    self.initialize()
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-33:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 91, in fetch_stock
    stock = Stock(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/stock.py", line 13, in initialize
    self.logo_url = self.yf_ticker.info.get('logo_url', None)
AttributeError: 'NoneType' object has no attribute 'get'
Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 105, in fetch_crypto
    crypto = Crypto(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/crypto.py", line 18, in initialize
    self.name = self.name.replace(' USD', '')
AttributeError: 'Crypto' object has no attribute 'name'
Exception in thread Thread-35:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/pi/led-stock-ticker/api/data.py", line 105, in fetch_crypto
    crypto = Crypto(symbol, currency)
  File "<string>", line 10, in __init__
  File "/home/pi/led-stock-ticker/data/ticker.py", line 31, in __post_init__
    self.initialize()
  File "/home/pi/led-stock-ticker/data/crypto.py", line 18, in initialize
    self.name = self.name.replace(' USD', '')
AttributeError: 'Crypto' object has no attribute 'name'

**Comment by feram18** [comment]
Investigating the issue. Apologies for the inconvenience.

**Comment by feram18** [comment]
It appears to be an error with `yfinance`'s data scrapper. This [issue](https://github.com/ranaroussi/yfinance/issues/1291) has some information on what's going on if you're interested in learning more. They seem to have a solution and will be making a new release with a fix soon. I will update the dependency version and push a new release as soon as it's up.

**Comment by feram18** [comment]
[v0.3.5](https://github.com/feram18/led-stock-ticker/releases/tag/v0.3.5) upgrades the `yfinance` dependency to resolve this issue. Be aware this dependency has been a bit unstable lately due to changes in Yahoo Finance's site.
