### ISSUE TITLE
Importing the numpy C-extensions failed

### ISSUE THREAD

**Issue by Freeboski** [feram18/led-stock-ticker#23]
**Describe the bug**
Hi, Ive tried a couple of fresh Pi installs but I keep getting the same issue when trying to run the command

```sudo python3 main.py --led-gpio-mapping="adafruit-hat" --led-slowdown-gpio=2```

The error I'm getting is:

``` 
File "/usr/local/lib/python3.9/dist-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory
```
Any idea's what it could be? I know another user had a similar issue but didnt really 'fix' it but tried a legacy os version.

**Configuration**
 - Raspberry Pi Model: 3B
 - Operative System: Raspberry Pi OS Full (32-bit) Released 2023-02-21
 - LED Matrix Size: 64x32
 - Display Adapter: Adafruit RGB Matrix Bonnet
 - Python Version: [Python 3.9
 - Arguments/Flags used to execute script: ```sudo python3 main.py --led-gpio-mapping="adafruit-hat" --led-slowdown-gpio=2```

**Screenshots/Logs**
```The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Feb 21 02:03:22 2023
pi@stockticker:~ $ sudo apt-get update
sudo apt-get install git python3-pip -y
Get:1 http://archive.raspberrypi.org/debian bullseye InRelease [23.6 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:3 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [316 kB                                                                                                                               ]
Get:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.                                                                                                                               2 MB]
Fetched 13.6 MB in 9s (1,552 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (20.3.4-4+rpt1+deb11u1).
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-cvs git-mediawiki git-svn
The following packages will be upgraded:
  git
1 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.
Need to get 4,704 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf git armhf 1:2                                                                                                                               .30.2-1+deb11u2 [4,704 kB]
Fetched 4,704 kB in 1s (6,568 kB/s)
apt-listchanges: Reading changelogs...
(Reading database ... 172062 files and directories currently installed.)
Preparing to unpack .../git_1%3a2.30.2-1+deb11u2_armhf.deb ...
Unpacking git (1:2.30.2-1+deb11u2) over (1:2.30.2-1+deb11u1) ...
Setting up git (1:2.30.2-1+deb11u2) ...
pi@stockticker:~ $ git clone --recursive https://github.com/feram18/led-stock-ticker.git
cd led-stock-ticker
chmod +x install.sh
./install.sh
Cloning into 'led-stock-ticker'...
remote: Enumerating objects: 1758, done.
remote: Counting objects: 100% (282/282), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 1758 (delta 166), reused 233 (delta 144), pack-reused 1476
Receiving objects: 100% (1758/1758), 49.06 MiB | 9.68 MiB/s, done.
Resolving deltas: 100% (1098/1098), done.
Updating files: 100% (78/78), done.
Submodule 'rpi-rgb-led-matrix' (https://github.com/hzeller/rpi-rgb-led-matrix.git) registered for path 'rpi-rgb-led-matrix'
Cloning into '/home/pi/led-stock-ticker/rpi-rgb-led-matrix'...
remote: Enumerating objects: 4946, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 4946 (delta 0), reused 0 (delta 0), pack-reused 4945
Receiving objects: 100% (4946/4946), 22.27 MiB | 6.87 MiB/s, done.
Resolving deltas: 100% (3422/3422), done.
Submodule path 'rpi-rgb-led-matrix': checked out 'a56338db0f003d5236f2ce98c73a591d64a70852'
___________________________________________________________________
   __   _______    ______           __     _______     __
  / /  / __/ _ \  / __/ /____  ____/ /__  /_  __(_)___/ /_____ ____
 / /__/ _// // / _\ \/ __/ _ \/ __/  '_/   / / / / __/  '_/ -_) __/
/____/___/____/ /___/\__/\___/\__/_/\_\   /_/ /_/\__/_/\_\__/_/
___________________________________________________________________

Updating system & installing Python 3
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-dev is already the newest version (3.9.2-3).
python3-dev set to manually installed.
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.

Installing rpi-rgb-led-matrix library...
make -C ./lib
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o gpio.o gpio.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o led-matrix.o led-matrix.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o options-initialize.o options-initialize.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o framebuffer.o framebuffer.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o thread.o thread.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o bdf-font.o bdf-font.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o graphics.o graphics.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o led-matrix-c.o led-matrix-c.cc
cc  -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -c -o hardware-mapping.o hardware-mapping.c
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o pixel-mapper.o pixel-mapper.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o multiplex-mappers.o multiplex-mappers.cc
g++ -I../include -W -Wall -Wextra -Wno-unused-parameter -O3 -g -fPIC  -DDEFAULT_HARDWARE='"regular"' -fno-exceptions -std=c++11 -c -o content-streamer.o content-streamer.cc
ar rcs librgbmatrix.a gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex-mappers.o content-streamer.o
g++ -shared -Wl,-soname,librgbmatrix.so.1 -o librgbmatrix.so.1 gpio.o led-matrix.o options-initialize.o framebuffer.o thread.o bdf-font.o graphics.o led-matrix-c.o hardware-mapping.o pixel-mapper.o multiplex
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/examples-api-use'
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o demo-main.o demo-main.cc
make -C ../lib
make[2]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
g++ demo-main.o -o demo -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o minimal-example.o minimal-example.cc
g++ minimal-example.o -o minimal-example -L../lib -lrgbmatrix -lrt -lm -lpthread
cc -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o c-example.o c-example.c
cc c-example.o -o c-example -L../lib -lrgbmatrix -lrt -lm -lpthread -lstdc++
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o text-example.o text-example.cc
g++ text-example.o -o text-example -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o scrolling-text-example.o scrolling-text-example.cc
g++ scrolling-text-example.o -o scrolling-text-example -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o clock.o clock.cc
g++ clock.o -o clock -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o ledcat.o ledcat.cc
g++ ledcat.o -o ledcat -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o input-example.o input-example.cc
g++ input-example.o -o input-example -L../lib -lrgbmatrix -lrt -lm -lpthread
g++ -I../include -Wall -O3 -g -Wextra -Wno-unused-parameter -c -o pixel-mover.o pixel-mover.cc
g++ pixel-mover.o -o pixel-mover -L../lib -lrgbmatrix -lrt -lm -lpthread
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
/usr/bin/python3 setup.py build --build-lib .
running build
running build_py
running build_ext
building 'core' extension
creating build
creating build/temp.linux-armv7l-3.9
creating build/temp.linux-armv7l-3.9/rgbmatrix
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -me -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/core.o -O3 -Wall
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -We-lrgbmatrix -o ./rgbmatrix/core.cpython-39-arm-linux-gnueabihf.so
building 'graphics' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -me -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/graphics.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/graphics.o -O3 -Wall
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Welib -lrgbmatrix -o ./rgbmatrix/graphics.cpython-39-arm-linux-gnueabihf.so
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
make -C ./lib
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
make[2]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/lib'
/usr/bin/python3 setup.py build --build-lib .
running build
running build_py
running build_ext
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
make -C bindings/python install
make[1]: Entering directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
/usr/bin/python3 setup.py install
running install
running build
running build_py
creating build/lib.linux-armv7l-3.9
creating build/lib.linux-armv7l-3.9/rgbmatrix
copying rgbmatrix/__init__.py -> build/lib.linux-armv7l-3.9/rgbmatrix
running build_ext
building 'core' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -me -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/core.o -O3 -Wall
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -We-lrgbmatrix -o build/lib.linux-armv7l-3.9/rgbmatrix/core.cpython-39-arm-linux-gnueabihf.so
building 'graphics' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -me -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/graphics.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/graphics.o -O3 -Wall
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Welib -lrgbmatrix -o build/lib.linux-armv7l-3.9/rgbmatrix/graphics.cpython-39-arm-linux-gnueabihf.so
running install_lib
creating /usr/local/lib/python3.9/dist-packages/rgbmatrix
copying build/lib.linux-armv7l-3.9/rgbmatrix/core.cpython-39-arm-linux-gnueabihf.so -> /usr/local/lib/python3.9/dist-packages/rgbmatrix
copying build/lib.linux-armv7l-3.9/rgbmatrix/graphics.cpython-39-arm-linux-gnueabihf.so -> /usr/local/lib/python3.9/dist-packages/rgbmatrix
copying build/lib.linux-armv7l-3.9/rgbmatrix/__init__.py -> /usr/local/lib/python3.9/dist-packages/rgbmatrix
byte-compiling /usr/local/lib/python3.9/dist-packages/rgbmatrix/__init__.py to __init__.cpython-39.pyc
running install_egg_info
Writing /usr/local/lib/python3.9/dist-packages/rgbmatrix-0.0.1.egg-info
make[1]: Leaving directory '/home/pi/led-stock-ticker/rpi-rgb-led-matrix/bindings/python'
Updating repository...
HEAD is now at 00430fb build: v0.3.11
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/feram18/led-stock-ticker
 * branch            master     -> FETCH_HEAD
Already up to date.
M       rpi-rgb-led-matrix
Note: switching to 'tags/v0.3.11'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 00430fb build: v0.3.11

Installing dependencies...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting jsonschema~=4.16.0
  Downloading https://www.piwheels.org/simple/jsonschema/jsonschema-4.16.0-py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 399 kB/s
Requirement already satisfied: lxml>=4.5.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.6.3)
Requirement already satisfied: numpy>=1.16.6 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.19.5)
Collecting multitasking~=0.0.9
  Downloading https://www.piwheels.org/simple/multitasking/multitasking-0.0.11-py3-none-any.whl (6.8 kB)
Collecting pandas>=0.23.1
  Downloading https://www.piwheels.org/simple/pandas/pandas-2.0.0-cp39-cp39-linux_armv7l.whl (38.7 MB)
     |████████████████████████████████| 38.7 MB 25 kB/s
Collecting pillow==9.3.0
  Downloading https://www.piwheels.org/simple/pillow/Pillow-9.3.0-cp39-cp39-linux_armv7l.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 3.2 MB/s
Collecting pytz>=2021.1
  Downloading https://www.piwheels.org/simple/pytz/pytz-2023.3-py3-none-any.whl (502 kB)
     |████████████████████████████████| 502 kB 3.2 MB/s
Collecting questionary>=1.10.0
  Downloading https://www.piwheels.org/simple/questionary/questionary-1.10.0-py3-none-any.whl (31 kB)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 9)) (2.25.1)
Collecting wheel>=0.37.0
  Downloading https://www.piwheels.org/simple/wheel/wheel-0.40.0-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 913 kB/s
Collecting yahooquery==2.3.0
  Downloading https://www.piwheels.org/simple/yahooquery/yahooquery-2.3.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 1.6 MB/s
Collecting lxml>=4.5.1
  Downloading https://www.piwheels.org/simple/lxml/lxml-4.9.2-cp39-cp39-linux_armv7l.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 141 kB/s
Collecting requests-futures>=1.0.0
  Downloading https://www.piwheels.org/simple/requests-futures/requests_futures-1.0.0-py3-none-any.whl (10 kB)
Collecting tqdm>=4.54.1
  Downloading https://www.piwheels.org/simple/tqdm/tqdm-4.65.0-py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 1.4 MB/s
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading https://www.piwheels.org/simple/pyrsistent/pyrsistent-0.19.3-cp39-cp39-linux_armv7l.whl (102 kB)
     |████████████████████████████████| 102 kB 3.2 MB/s
Collecting attrs>=17.4.0
  Downloading https://www.piwheels.org/simple/attrs/attrs-23.1.0-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 2.1 MB/s
Collecting tzdata>=2022.1
  Downloading https://www.piwheels.org/simple/tzdata/tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     |████████████████████████████████| 341 kB 3.0 MB/s
Collecting python-dateutil>=2.8.2
  Downloading https://www.piwheels.org/simple/python-dateutil/python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 7.8 MB/s
Collecting numpy>=1.16.6
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.24.2-cp39-cp39-linux_armv7l.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 34 kB/s
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in /usr/lib/python3/dist-packages (from questionary>=1.10.0->-r requirements.txt (line 8)) (3.0.14)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23.1->-r requirements.txt (line 5)) (1.16.0)
Installing collected packages: tzdata, pytz, python-dateutil, numpy, tqdm, requests-futures, pyrsistent, pandas, lxml, attrs, yahooquery, wheel, questionary, pillow, multitasking, jsonschema
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.1
    Not uninstalling python-dateutil at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'python-dateutil'. No files were found to uninstall.
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Not uninstalling numpy at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'numpy'. No files were found to uninstall.
  Attempting uninstall: lxml
    Found existing installation: lxml 4.6.3
    Not uninstalling lxml at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'lxml'. No files were found to uninstall.
  Attempting uninstall: wheel
    Found existing installation: wheel 0.34.2
    Not uninstalling wheel at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'wheel'. No files were found to uninstall.
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.1.2
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Pillow'. No files were found to uninstall.
Successfully installed attrs-23.1.0 jsonschema-4.16.0 lxml-4.9.2 multitasking-0.0.11 numpy-1.24.2 pandas-2.0.0 pillow-9.3.0 pyrsistent-0.19.3 python-dateutil-2.8.2 pytz-2023.3 questionary-1.10.0 requests-fut
Creating new config.json file...
Set your preferences using the command ./config.py
Update completed

If there are no errors shown above, installation was successful.
To make sure your matrix is working properly, execute the samples located in ./rpi-rgb-led-matrix/bindings/python/samples
pi@stockticker:~/led-stock-ticker $ ./update.sh
Updating repository...
HEAD is now at 00430fb build: v0.3.11
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/feram18/led-stock-ticker
 * branch            master     -> FETCH_HEAD
Already up to date.
M       rpi-rgb-led-matrix
HEAD is now at 00430fb build: v0.3.11

Installing dependencies...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: jsonschema~=4.16.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 1)) (4.16.0)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (4.9.2)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (1.24.2)
Requirement already satisfied: multitasking~=0.0.9 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (0.0.11)
Requirement already satisfied: pandas>=0.23.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (2.0.0)
Requirement already satisfied: pillow==9.3.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 6)) (9.3.0)
Requirement already satisfied: pytz>=2021.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (2023.3)
Requirement already satisfied: questionary>=1.10.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (1.10.0)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 9)) (2.25.1)
Requirement already satisfied: wheel>=0.37.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 10)) (0.40.0)
Requirement already satisfied: yahooquery==2.3.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 11)) (2.3.0)
Requirement already satisfied: tqdm>=4.54.1 in /usr/local/lib/python3.9/dist-packages (from yahooquery==2.3.0->-r requirements.txt (line 11)) (4.65.0)
Requirement already satisfied: requests-futures>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from yahooquery==2.3.0->-r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema~=4.16.0->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema~=4.16.0->-r requirements.txt (line 1)) (0.19.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.23.1->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=0.23.1->-r requirements.txt (line 5)) (2023.3)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in /usr/lib/python3/dist-packages (from questionary>=1.10.0->-r requirements.txt (line 8)) (3.0.14)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23.1->-r requirements.txt (line 5)) (1.16.0)
Update completed
pi@stockticker:~/led-stock-ticker $ ./config.py
📈 Enter stocks:  (Separate each ticker by a space) TSLA AMZN MSFT
💰 Enter cryptos:  (Separate each ticker by a space) BTC ETH LTC
💱 Enter forex pairs:  (Separate each pair by a space) USD/EUR EUR/JPY GBP/USD
💲 Select currency: (Use arrow keys)
   BOB
   BRL
   BSD
   BWP
   BYN
   BZD
   CAD
   CHF
   CLP
   CNY
   COP
   CRC
   CUP
   CZK
   DKK
   EGP
   EUR
   FJD
   FKP
 » GBP
   GEL
   GGP
   GHS
   GIP
   GTQ
   GYD
   HKD
   HNL
   HRK
   HUF
   IDR
   ILS
   IMP
   INR
   IRR
   JMD
   JPY
   KES
   KGS
   KPW
   KRW
   KYD
   LAK
   LBP
   LKR
   LRD
   MAD
   MKD
   MNT
   MUR
   MXN
   MYR
   MZN
   NAD
   NGN
   NIO
   NOK
   NPR
   NZD
   OMR
   PAB
   PEN
   PHP
   PKR
   PLN
   PYG
   QAR
   RON
   RSD
   RUB
   SAR
   SBD
   SCR
   SEK
   SGD
   SHP
   SOS
   SRD
   SYP
   THB
   TRY
   TTD
   TWD
   UAH
   USD
💲 Select currency: GBP
🕒 Select clock format: 24h
📅 Select date format: 20/04/2023
🔄 Select rotation rate: 5
𒏬  Select update rate: 5
🖼 Show company stock & crypto logos? History chart will be displayed otherwise:  Yes
✅ Setup is complete!
pi@stockticker:~/led-stock-ticker $ sudo python3 main.py --led-gpio-mapping="adafruit-hat" --led-slowdown-gpio=2
Traceback (most recent call last):
  File "/home/pi/led-stock-ticker/main.py", line 9, in <module>
    from api.data import Data
  File "/home/pi/led-stock-ticker/api/data.py", line 9, in <module>
    from data.crypto import Crypto
  File "/home/pi/led-stock-ticker/data/crypto.py", line 3, in <module>
    from data.ticker import Ticker
  File "/home/pi/led-stock-ticker/data/ticker.py", line 5, in <module>
    import yahooquery
  File "/usr/local/lib/python3.9/dist-packages/yahooquery/__init__.py", line 6, in <module>
    from .research import Research  # noqa
  File "/usr/local/lib/python3.9/dist-packages/yahooquery/research.py", line 4, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.9/dist-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libcblas.so.3: cannot open shared object file: No such file or directory

pi@stockticker:~/led-stock-ticker $
```

**Comment by feram18** [comment]
I've encountered a pretty similar issue recently on another project where a dependency was expecting a library to be already present. In my case it was looking for a C library that the OS did not come with.

Try `sudo apt-get install libatlas-base-dev`.
