### ISSUE TITLE
YahooQuery Failing

### ISSUE THREAD

**Issue by Berson12-tkr** [feram18/led-stock-ticker#39]
when initiating the Ticker, the screen shows the red and blu arrows and version number, but then stops and fails, when debugging, it appears the Yahoo connection is timing out for me, unsure why.

Debug details below.

09/10/2024 11:55:22 AM ERROR: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v6/finance/quoteSummary/TSLA?modules=price&formatted=false&lang=en-US&region=US&corsDomain=finance.yahoo.com (Caused by ResponseError('too many 404 error responses'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='query2.finance.yahoo.com', port=443): Max retries exceeded with url: /v6/finance/quoteSummary/TSLA?modules=price&formatted=false&lang=en-US&region=US&corsDomain=finance.yahoo.com (Caused by ResponseError('too many 404 error responses'))

**Comment by Berson12-tkr** [comment]
Pardon my ignorance, upon further investigating it appears you had fixed the issue some months ago, my version was at 0.3.15 so required updating, will confirm once updated its resolved.
